# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "price-matrix-app"
client_id = ""
application_url = "https://localhost"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
# https://shopify.dev/docs/api/usage/access-scopes
scopes = "write_products,read_customers,write_draft_orders"

[auth]
redirect_urls = [
  "https://localhost/auth/callback",
  "https://localhost/auth/shopify/callback",
  "https://localhost/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = [ "customers/data_request" ]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = [ "customers/redact" ]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = [ "shop/redact" ]
uri = "/webhooks"

[pos]
embedded = false
